name: Staging Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the main branch
  push:
    tags:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: "ubuntu-latest"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: '${{ secrets.PROD_GCP_CREDENTIALS }}'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - id: "deploy"
        name: Deploy app to Google Cloud Function
        run: |
          gcloud functions deploy hello-http \
          --gen2 \
          --runtime=python311 \
          --region=asia-southeast1 \
          --source=./ \
          --entry-point=hello_http \
          --trigger-http \
          --allow-unauthenticated
